### ISSUE TITLE
support customize filename & network service support

### ISSUE THREAD

**Issue by KevinTroyT** [dfinity/keysmith#18]
customize filename
------
use `keysmith <command> <filename>` to generate/get mnemonic file with customize filename.

network service
-----

use `keysmith netservice start` to start a network service support by GIN. API document include

[https://github.com/KevinTroyT/keysmith](https://github.com/KevinTroyT/keysmith)

**Comment by enzoh** [comment]
Regarding custom file names, you can change the name of the input file with `-f` and the name of the output file with `-o`. You can also use `-f=-` for `stdin` and `-o=-` for `stdout`.

Regarding your net service, this seems to escape the scope of this repository, which is purely focused on key derivation. I think it makes sense to separate concerns here, wouldn't you agree? This net service of yours can easily exist independently and simply call into `keysmith`'s libraries.
