### ISSUE TITLE
support for 24 word seed phrases

### ISSUE THREAD

**Issue by jancamenisch** [dfinity/keysmith#27]
Would love to have that, thanks!

**Comment by enzoh** [comment]
Thanks @jancamenisch, I just released [v1.6.2](https://github.com/dfinity/keysmith/releases/tag/v1.6.2), which should resolve this issue. The `generate` command now allows a user to specify the bits of entropy using `-b`. Valid values are `128`, `160`, `192`, `224`, `256` for 12-, 15-, 18-, 21-, and 24-word seed phrases, respectively. `128` bits is still the default behavior.
