### ISSUE TITLE
Issues installing on MacOS

### ISSUE THREAD

**Issue by ByronBecker** [dfinity/keysmith#34]
## Issue
Was recently following [this wiki](https://wiki.internetcomputer.org/wiki/How-To:_Create_an_NNS_motion_proposal#Check_dashboard_to_see_proposal_was_successful) installing both quill and keysmith to create an NNS Proposal and wasn't able to get keysmith installed (but Quill works fine).

## My Setup
MacBook Pro 2019 - 2.3 GHz 8-Core Intel Core i9
macOS Monterey - Version 12.2.1

## Steps taken (keysmith-darwin-arm64.tar.gz)
1. Download [keysmith-darwin-arm64.tar.gz](https://github.com/dfinity/keysmith/releases/download/v1.6.2/keysmith-darwin-arm64.tar.gz) from releases.
2. Follow the [installation instructions](https://github.com/dfinity/keysmith#install) in the README.
3. Attempt to invoke keysmith with `% keysmith`
4. Result: `zsh: bad CPU type in executable: keysmith`

After the darwin-arm64 seemed to not be compatible, I tried the linux-arm64 executable just to make sure, but of course no cigar there.

## Question
I see that quill has a specific mac-os release but keysmith does not. Does this mean that MacOS users should use any capable tool to generate a SHA256 key pair and pass the public key to quill, or should we specifically use keysmith?

**Comment by ByronBecker** [comment]
Tagging @enzoh @timohanke for visibility.

**Comment by ByronBecker** [comment]
Closing, as I just saw the new Deprecation PR come in - will move to quill

**Comment by enzoh** [comment]
@ByronBecker You downloaded the ARM binary, but you are using an Intel computer. You need to download the correct binary for your system. For you that would be [keysmith-darwin-amd64.tar.gz](https://github.com/dfinity/keysmith/releases/download/v1.6.2/keysmith-darwin-amd64.tar.gz).
